[general]
import = [
    "~/.config/alacritty/coolnight.toml"
]

[window]
padding.x = 10
padding.y = 10

decorations = "Full"
startup_mode = "Windowed"
decorations_theme_variant = "Dark"

[font] 
size = 15


