[".local/bin/mise"]
type = "file"
executable = true
url = "https://mise.jdx.dev/mise-latest-{{- if eq .chezmoi.os "darwin" -}}macos{{- else -}}{{.chezmoi.os}}{{- end -}}-{{- if eq .chezmoi.arch "amd64" -}}x64{{- else -}}{{.chezmoi.arch}}{{- end -}}"
