views:
  gateway.networking.k8s.io/v1/httproutes:
    sortColumn: GATEWAY:asc
    columns:
      - NAMESPACE
      - NAME
      - GATEWAY:.spec.parentRefs[*].name
      - HOSTNAMES:.spec.hostnames
      - SERVICE:.spec.rules[*].backendRefs[*].name
      - PORT:.spec.rules[*].backendRefs[*].port
      - ACCEPTED:.status.parents[0].conditions[?(@.type=="Accepted")].reason
      - RESOLVED:.status.parents[0].conditions[?(@.type=="ResolvedRefs")].reason
      - AGE